const $=id=>document.getElementById(id);
function apiUrl(action,extra={}){if(!INVEST_API_BASE||INVEST_API_BASE.includes("KEEP_YOUR")||INVEST_API_BASE.includes("PASTE_YOUR"))throw new Error("請保留目前正式使用中的 config.js");const u=new URL(INVEST_API_BASE);u.searchParams.set("action",action);if(INVEST_API_KEY)u.searchParams.set("key",INVEST_API_KEY);Object.entries(extra||{}).forEach(([k,v])=>u.searchParams.set(k,v));return u}
function fetchJson(action,extra={}){return new Promise((resolve,reject)=>{const cb="__investApiCb_"+Date.now()+"_"+Math.floor(Math.random()*1e6),u=apiUrl(action,extra);u.searchParams.set("callback",cb);const s=document.createElement("script");let timer;function cleanup(){clearTimeout(timer);if(s.parentNode)s.parentNode.removeChild(s);try{delete window[cb]}catch(_){window[cb]=undefined}}window[cb]=json=>{cleanup();if(!json||json.ok!==true)return reject(new Error((json&&json.error)||"API error"));resolve(json.data)};s.src=u.toString();s.async=true;s.onerror=()=>{cleanup();reject(new Error("API 載入失敗"))};timer=setTimeout(()=>{cleanup();reject(new Error("API 連線逾時"))},15000);document.head.appendChild(s)})}
function num(v,d=2){if(v===null||v===undefined||v==="")return"—";const n=Number(v);if(!Number.isFinite(n))return"—";return n.toFixed(d).replace(/\.00$/,"")}
function pct(v){if(v===null||v===undefined||v==="")return"—";const n=Number(v);if(!Number.isFinite(n))return"—";return`${n>0?"+":""}${n.toFixed(2)}%`}
function clsNum(v){return Number(v)>=0?"pos":"neg"}function actionClass(a=""){if(a.includes("買進")||a.includes("BUY"))return"buy";if(a.includes("準備")||a.includes("READY"))return"ready";return"watch"}
let SWING=[],SHORT=[];
function renderOverview(){const s=SWING.filter(x=>String(x.action||"").includes("買進")||String(x.action||"").includes("準備")).length,h=SHORT.filter(x=>String(x.action||"").includes("買進")||String(x.action||"").includes("準備")).length;$("swingBuyCount").textContent=`${s} / ${SWING.length||0}`;$("shortBuyCount").textContent=`${h} / ${SHORT.length||0}`;if(SHORT.length){const a=[...SHORT].sort((x,y)=>(y.shortScore||0)-(x.shortScore||0))[0],b=[...SHORT].sort((x,y)=>(y.winRate20D||0)-(x.winRate20D||0))[0];$("bestShortScore").textContent=num(a.shortScore);$("bestShortName").textContent=`${a.stockName} ${a.stockId}`;$("best20Win").textContent=pct(b.winRate20D);$("best20Name").textContent=`${b.stockName} ${b.stockId}`}}
function renderSwingTable(data){SWING=data.items||[];const root=$("swingTable");root.innerHTML="";SWING.forEach(x=>{const tr=document.createElement("tr");tr.className="clickable";tr.innerHTML=`<td>${x.rank}</td><td class="stock-cell"><b>${x.stockName}</b><small>${x.stockId}</small></td><td><span class="action ${actionClass(x.action)}">${x.action||"—"}</span></td><td><b>${num(x.decisionScore)}</b></td><td>${pct(x.winRate45D)}</td><td class="${clsNum(x.expectedValue45D)}">${pct(x.expectedValue45D)}</td>`;tr.addEventListener("click",()=>showSwingDetail(x));root.appendChild(tr)})}
function renderShortTable(data){SHORT=data.items||[];const root=$("shortTable");root.innerHTML="";SHORT.forEach(x=>{const tr=document.createElement("tr");tr.className="clickable";tr.innerHTML=`<td>${x.rank}</td><td class="stock-cell"><b>${x.stockName}</b><small>${x.stockId}</small></td><td><span class="action ${actionClass(x.action)}">${x.action||"—"}</span></td><td><b>${num(x.shortScore)}</b></td><td>${pct(x.winRate20D)}</td><td class="${clsNum(x.expectedValue20D)}">${pct(x.expectedValue20D)}</td>`;tr.addEventListener("click",()=>showShortDetail(x));root.appendChild(tr)})}
function showSwingDetail(x){$("detailPanel").classList.remove("hidden");$("detailTitle").textContent=`${x.stockName} ${x.stockId}`;$("detailAction").className=`action ${actionClass(x.action)}`;$("detailAction").textContent=x.action||"—";$("detailScore").textContent=num(x.decisionScore);$("detailStrategy").textContent=x.strategyPath||"波段 30–45D";$("detailEntry").textContent=`${num(x.entryLow)} ～ ${num(x.entryHigh)}`;$("detailStop").textContent=num(x.stopLoss);$("detailT1").textContent=num(x.target1);$("detailT2").textContent=num(x.target2);$("detailWinLabel1").textContent="30D 歷史經驗勝率";$("detailWinLabel2").textContent="45D 歷史經驗勝率";$("detailWin1").textContent=pct(x.winRate30D);$("detailWin2").textContent=pct(x.winRate45D);$("detailEV").textContent=pct(x.expectedValue45D);$("detailMAE").textContent=pct(x.mae45D);$("detailReason").textContent="依個股歷史走勢統計，非相同訊號回測結果。";$("detailPanel").scrollIntoView({behavior:"smooth",block:"start"})}
function showShortDetail(x){$("detailPanel").classList.remove("hidden");$("detailTitle").textContent=`${x.stockName} ${x.stockId}`;$("detailAction").className=`action ${actionClass(x.action)}`;$("detailAction").textContent=x.action||"—";$("detailScore").textContent=num(x.shortScore);$("detailStrategy").textContent=`短線 ${x.holdingDays||"10–20D"}｜風險 ${x.riskLevel||"—"}`;$("detailEntry").textContent=`${num(x.entryLow)} ～ ${num(x.entryHigh)}`;$("detailStop").textContent=num(x.stopLoss);$("detailT1").textContent=num(x.target1);$("detailT2").textContent=num(x.target2);$("detailWinLabel1").textContent="10D 歷史經驗勝率";$("detailWinLabel2").textContent="20D 歷史經驗勝率";$("detailWin1").textContent=pct(x.winRate10D);$("detailWin2").textContent=pct(x.winRate20D);$("detailEV").textContent=pct(x.expectedValue20D);$("detailMAE").textContent=pct(x.mae20D);$("detailReason").textContent=x.reason||"依個股歷史走勢統計，非相同訊號回測結果。";$("detailPanel").scrollIntoView({behavior:"smooth",block:"start"})}
function renderHealth(data){const root=$("healthGrid");root.innerHTML="";[["Top5",data.sheets?.top5?.rows],["ShortTop5",data.sheets?.shortTop5?.rows],["Final",data.sheets?.final?.rows],["績效",data.sheets?.performance?.rows]].forEach(([n,v])=>{const el=document.createElement("div");el.className="health-card";el.innerHTML=`<div class="name">${n}</div><div class="value">${v??"—"}</div>`;root.appendChild(el)})}
function renderPerformance(data){const root=$("performanceList");root.innerHTML="";if(!data.items?.length){root.innerHTML=`<div class="health-card">尚未累積績效資料</div>`;return}data.items.slice(0,8).forEach(x=>{const el=document.createElement("div");el.className="performance-row";el.innerHTML=`<div><b>${x.stockId} ${x.stockName}</b><div class="small">${x.tradeDate}</div></div><div><div class="small">5D</div><b class="${clsNum(x.return5D)}">${pct(x.return5D)}</b></div><div><div class="small">20D</div><b class="${clsNum(x.return20D)}">${pct(x.return20D)}</b></div><div><div class="small">45D</div><b class="${clsNum(x.return45D)}">${pct(x.return45D)}</b></div>`;root.appendChild(el)})}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
async function loadAll(){$("refreshBtn").disabled=true;try{const[health,swing,short,perf]=await Promise.all([fetchJson("health"),fetchJson("top5"),fetchJson("shorttop5"),fetchJson("performance",{limit:10})]);$("tradeDate").textContent=swing.tradeDate||short.tradeDate||health.latestArchiveTradeDate||"—";renderSwingTable(swing);renderShortTable(short);renderOverview();renderHealth(health);renderPerformance(perf);toast("資料已更新")}catch(err){console.error(err);toast(err.message||"載入失敗")}finally{$("refreshBtn").disabled=false}}
function scrollToId(id){const el=$(id);if(el)el.scrollIntoView({behavior:"smooth",block:"start"})}
document.querySelectorAll("[data-scroll]").forEach(btn=>btn.addEventListener("click",()=>scrollToId(btn.dataset.scroll)));$("refreshBtn").addEventListener("click",loadAll);if("serviceWorker"in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"))}loadAll();